import Head from 'next/head'
import Main from '../../components/Main'
import About from '../../components/About'
import Skills from '../../components/Skills'
import Project from '../../components/Project'
import Contact from '../../components/Contact'
export default function Home() {
  return (
    <div>
      <Head>
        <title>Rishi Mishra's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main/>
      <About/>
      <Project/>
      <Skills/>
      <Contact/>
    </div>
  )
}
